puts "*************************************************"
puts "*************************************************"
puts "**                                             **"
puts "**            Twitter  console                 **"
puts "**                                             **" 
puts "**           1. send twitts                    **"
puts "**           2. check twitts                   **"
puts "**           3. leave                          **"
puts "**                                             **"
puts "**                                             **"
puts "**          give me your choice please:        **"
puts "**                                             **"
puts "*************************************************"
puts "*************************************************"
opt = gets.chomp

